apiVersion: v1
kind: Deployment
metadata:
  name: odoo
  namespace: tp-odoo
  labels:
    app: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: odoo
          image: odoo:14
          ports:
            - containerPort: 8069
              protocol: TCP
          env:
            - name: HOST
              value: db
            - name: PORT
              value: 5432
            - name: USER
              value: odoo
            - name: PASSWORD
              valueFrom:
			    name: odoo-password
				key: odoo
          volumeMounts:
            - name: pvc-odoo-claim
              mountPath: /var/www/odoo
      volumes:
        - name: pvc-odoo-claim
          persistentVolumeClaim:
            claimName: pvc-odoo-claim
