apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: tp-odoo
spec:
  selector:
    type: NodePort
    app: web
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069