apiVersion: v1
kind: Deployment
metadata:
  name: postgresql
  namespace: tp-odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-odoo
  template:
    metadata:
      labels:
        app: data-odoo
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PASSWORD
          value: myodoo
        - name: POSTGRES_PASSWORD
          valueFrom:
	    name: postgresql_password
	    key: odoo
        - name: POSTGRES_USER
          value: odoo
        - name: PGDATA
          value: db-data
          image: postgres:13
          ports:
            - name: http            
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/odoo
              name: pvc-odoo-postgresql-claim
      volumes:
        - name: pvc-odoo-postgresql-claim
          persistentVolumeClaim:
            claimName: pvc-odoo-postgresql-claim
