apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: tp-odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-odoo
  template:
    metadata:
      labels:
        app: data-odoo
    spec:
      containers:
        - name: odoo
          image: postgres:13
          ports:            
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-password
                  key: odoo
            - name: POSTGRES_USER
              value: odoo
            - name: PGDATA
              value: db-data
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pvc-odoo-postgresql-claim
      volumes:
        - name: pvc-odoo-postgresql-claim
          persistentVolumeClaim:
            claimName: pvc-odoo-postgresql-claim
