apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo-postgresql-claim
  namespace: tp-odoo
  labels:
    app: odoo-postgresql
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
