apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo-claim
  labels:
    app: web
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi